use super::super::{macros::award, types::*};
use super::facts::mahjong_fan;
use leocard_mahjong::Fan;

macro_rules! fan {
    ($id:literal, $title:literal, $tier:ident, $fan:ident, $description:literal) => {
        award!(
            "leocard:mahjong/",
            Mahjong,
            $id,
            $title,
            $tier,
            $description,
            |event| u64::from(mahjong_fan(event, Fan::$fan)),
            1,
            Lifetime
        )
    };
}

pub(super) const DEFINITIONS: &[AchievementDefinition] = &[
    fan!(
        "big_four_winds",
        "风神召唤",
        Silver,
        BigFourWinds,
        "和出番种「大四喜」"
    ),
    fan!(
        "big_three_dragons",
        "三位一体",
        Silver,
        BigThreeDragons,
        "和出番种「大三元」"
    ),
    fan!(
        "all_green",
        "绿满乾坤",
        Silver,
        AllGreen,
        "和出番种「绿一色」"
    ),
    fan!(
        "nine_gates",
        "莲灯九转",
        Silver,
        NineGates,
        "和出番种「九莲宝灯」"
    ),
    fan!(
        "four_kongs",
        "四柱擎天",
        Silver,
        FourKongs,
        "和出番种「四杠」"
    ),
    fan!(
        "seven_shifted_pairs",
        "七星连珠",
        Silver,
        SevenShiftedPairs,
        "和出番种「连七对」"
    ),
    fan!(
        "thirteen_orphans",
        "国士无双",
        Silver,
        ThirteenOrphans,
        "和出番种「十三幺」"
    ),
    fan!(
        "all_terminals",
        "九九归一",
        Silver,
        AllTerminals,
        "和出番种「清幺九」"
    ),
    fan!(
        "little_four_winds",
        "风神眷顾",
        Silver,
        LittleFourWinds,
        "和出番种「小四喜」"
    ),
    fan!(
        "little_three_dragons",
        "三元聚首",
        Silver,
        LittleThreeDragons,
        "和出番种「小三元」"
    ),
    fan!(
        "all_honors",
        "字字珠玑",
        Silver,
        AllHonors,
        "和出番种「字一色」"
    ),
    fan!(
        "four_concealed_pungs",
        "四暗藏锋",
        Silver,
        FourConcealedPungs,
        "和出番种「四暗刻」"
    ),
    fan!(
        "pure_terminal_chows",
        "双龙戏珠",
        Silver,
        PureTerminalChows,
        "和出番种「一色双龙会」"
    ),
    fan!(
        "quadruple_chow",
        "四顺同源",
        Silver,
        QuadrupleChow,
        "和出番种「一色四同顺」"
    ),
    fan!(
        "four_pure_shifted_pungs",
        "节节高升",
        Silver,
        FourPureShiftedPungs,
        "和出番种「一色四节高」"
    ),
    fan!(
        "mixed_shifted_chows",
        "初窥门径",
        Bronze,
        MixedShiftedChows,
        "和出番种「三色三步高」"
    ),
    fan!(
        "mixed_triple_chow",
        "读起来就是朗朗上口",
        Bronze,
        MixedTripleChow,
        "和出番种「三色三同顺」"
    ),
    fan!(
        "mixed_straight",
        "龙飞凤舞",
        Bronze,
        MixedStraight,
        "和出番种「花龙」"
    ),
    fan!(
        "pure_straight",
        "一气呵成",
        Bronze,
        PureStraight,
        "和出番种「清龙」"
    ),
    fan!(
        "half_flush",
        "从左往右打就可以了",
        Bronze,
        HalfFlush,
        "和出番种「混一色」"
    ),
    fan!(
        "pure_shifted_chows",
        "没有那么难呢",
        Bronze,
        PureShiftedChows,
        "和出番种「一色三步高」"
    ),
    fan!(
        "all_types",
        "五谷丰登",
        Bronze,
        AllTypes,
        "和出番种「五门齐」"
    ),
    fan!(
        "all_pungs",
        "有碰才有杠",
        Bronze,
        AllPungs,
        "和出番种「碰碰和」"
    ),
    fan!(
        "seven_pairs",
        "有碰也不碰",
        Bronze,
        SevenPairs,
        "和出番种「七对」"
    ),
    fan!(
        "outside_hand",
        "拖衣带水",
        Bronze,
        OutsideHand,
        "和出番种「全带幺」"
    ),
    fan!(
        "knitted_straight",
        "奇怪的组合",
        Bronze,
        KnittedStraight,
        "和出番种「组合龙」"
    ),
    fan!(
        "lesser_honors_knitted",
        "破烂手牌的出路",
        Bronze,
        LesserHonorsAndKnittedTiles,
        "和出番种「全不靠」"
    ),
    fan!(
        "upper_four",
        "我喜欢大的",
        Bronze,
        UpperFour,
        "和出番种「大于五」"
    ),
    fan!(
        "lower_four",
        "我喜欢小的",
        Bronze,
        LowerFour,
        "和出番种「小于五」"
    ),
    fan!(
        "chicken_hand",
        "无中生有",
        Bronze,
        ChickenHand,
        "和出番种「无番和」"
    ),
    fan!(
        "melded_hand",
        "不能没有你",
        Bronze,
        MeldedHand,
        "和出番种「全求人」"
    ),
    fan!(
        "robbing_kong",
        "那个杠不成立！",
        Bronze,
        RobbingTheKong,
        "和出番种「抢杠和」"
    ),
    fan!(
        "replacement_win",
        "高岭之花",
        Bronze,
        OutWithReplacementTile,
        "和出番种「杠上开花」"
    ),
    fan!(
        "last_tile_claim",
        "笑到最后",
        Bronze,
        LastTileClaim,
        "和出番种「海底捞月」"
    ),
];
